
---
title: "Untitled"
author: "Zulma"
date: "18 December 2017"
output: html_document
---

Imperial College London
Princeton University
Pan-American Health Organization 

Symposium
“How can modelling contribute to achieving the goals for Chagas disease in the horizon 2020 and beyond?

Feb 14th–16th, 2018
Imperial College London, South Kensington Campus (Prince's Gardens, 58 and 170 Prince’s Gate)

Chagas disease remains as a major cause of heart disease morbidity and mortality in Latin American countries. In the last three decades, most endemic countries have made great strides towards the control of Chagas disease by implementing mainly vector and blood transfusion control. However, the impact of such interventions has, by and large, not been rigorously quantified, and questions remain as how to address old and new challenges as countries progress towards the goals proposed by the World Health Organization (WHO) in the horizon 2020 and beyond. These goals are aimed to achieve interruption of intra-domiciliary (vectorial) transmission in all endemic countries and to have all infected/ill patients under care. However, estimates of the current status of intra-domiciliary transmission and burden of disease in endemic countries remain poorly documented, making it difficult to ascertain progress, identify areas that need strengthening, and make programmatic decisions about deploying the most cost-effective interventions.

The Department of Infectious Disease Epidemiology at Imperial College London in collaboration with the Pan American Health Organization (PAHO), Princeton University, and the Neglected Tropical Disease Modelling Consortium is convening a symposium and workshop to define overarching challenges and research priorities, explore opportunities, develop collaborations, and build strategies towards a research agenda for rigorous mathematical modelling to help measure and inform progress on control and elimination of Chagas disease in Latin America.

Specifically, discussions will be centred around the theme of how can transmission dynamics and statistical models help to highlight country programmes priorities and measure the progress made, and how can endemic countries help to inform the models and make best use of them to plan and deploy country-specific and cost-effective interventions.

The meeting will bring together representatives of international organizations, scientific researchers, programme managers, non-government and non-profit organizations, industry partners, government representatives, and community stakeholders to identify and articulate opportunities for long-term, highly impactful and country-relevant collaborative research.

Day 1 (14th February): Afternoon: Closed meeting PAHO–Imperial College London–Princeton University

Day 2 (15th February): Invited talks (and posters) on the epidemiological and control status of Chagas disease in Latin America, identified gaps and the role of mathematical modelling in bridging these gaps

Day 3 (16th February): Workshop (breakout sessions) and discussion for the preparation of a Meeting Report on “How can Chagas disease modelling best assist endemic countries to reach their control and elimination goals in the horizon 2020 and beyond”
